### ISSUE TITLE
:bug: In Lab.tsx, variable "orderItemsArray" is Array of size one, but "orderItemsArray[0]" is undefined

### ISSUE THREAD

**Issue by VincentWENDLING** [VincentWENDLING/gestion-stock#1]
So I try to fetch all the "order-item-container" objects linked to an order from the database. (As well as the restaurant which ordered all these items).

```
let orderItemsArray:Array<any> = []
    
    ordersArray.forEach(async (order:any)=>{
        let { data: products, errorProducts } = await supabase
            .from('order-item-container')
            .select('*')
            .eq('order_id', order.id)

        let { data: restaurant, errorRestaurant  } = await supabase
            .from('restaurant')
            .select('name, address')
            .eq('id', order.restaurant_id)

        orderItemsArray.push({
            items: products,
            restaurant: (restaurant !== null) ? restaurant[0] : {}
        })
    })
```

When I write this line of code `console.log(orderItemsArray)` I get the following result on the console:
![screenConsole](https://user-images.githubusercontent.com/106516331/176757684-daefee44-f1ae-4d18-9632-7347aa976d36.png)

But if I write `console.log(orderItemsArray[0])` I get this:
![screenConsole2](https://user-images.githubusercontent.com/106516331/176757671-939b7f5a-de5e-4a84-975a-d49375639672.png)

.. which doesn't make sense since the array is supposed to be of size one...

Any idea what's wrong?

**Comment by lionelhorn** [comment]
https://github.com/VincentWENDLING/gestion-stock/blob/430fff3c81c65dd905364cfaac8bf82ea6d46448/src/pages/Lab.tsx#L29-L48

https://github.com/VincentWENDLING/gestion-stock/blob/430fff3c81c65dd905364cfaac8bf82ea6d46448/src/pages/Lab.tsx#L48

**Comment by VincentWENDLING** [comment]
Thanks Lionel :)
